checks:
  go: true

build:
  environment:
    memcached: false
    postgresql: false
    redis: false
    mysql: false
    neo4j: false
    rabbitmq: false
    elasticsearch: false

  # Run after dependencies
  project_setup:
    override:
      - git clone https://github.com/nafigator/zapper.git
      - cd zapper
      - git checkout $SCRUTINIZER_BRANCH
      - git pull --rebase origin main
      - go mod tidy
      - go install github.com/axw/gocov/gocov@latest
      - go install github.com/AlekSi/gocov-xml@latest

  nodes:
    analysis:
      project_setup:
        override:
          - true
      environment:
        go:
          version: go1.20.4
      tests:
        override:
          - go-scrutinizer-run --enable-security-analysis
          - govet-run
          - golint-run
    tests:
      environment:
        go:
          version: go1.20.4

  tests:
#    before:
#      -
#        command: go mod tidy && go mod vendor
    override:
      -
        command: go test -gcflags=-l -coverprofile=/home/scrutinizer/build/zapper/cover.out
        coverage:
          file: /home/scrutinizer/build/zapper/cover.out
          format: go-cc
