# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.55.2

          # Optional: working directory, useful for monorepos
          #working-directory: headers

          # Optional: golangci-lint command line arguments.
          #
          # Note: By default, the `.golangci.yml` file should be at the root of the repository.
          # The location of the configuration file can be changed by using `--config=`
          # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true, then all caching functionality will be completely disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: '**/go.sum'
          go-version: '1.20'

      - name: Test conf package
        run: go test -C conf -v -gcflags=-l ./... -race -coverprofile=./conf.out -covermode=atomic

      - name: Test writer package
        run: go test -C writer -v -gcflags=-l ./... -race -coverprofile=./writer.out -covermode=atomic

      - name: Test zapper package
        run: go test -v ./... -gcflags=-l -race -coverprofile=./zapper.out -covermode=atomic

      - name: Check conf package coverage
        uses: vladopajic/go-test-coverage@v2.11.2
        with:
          profile: ./conf/conf.out
          local-prefix: github.com/nafigator/zapper
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100

      - name: Check writer package coverage
        uses: vladopajic/go-test-coverage@v2.11.2
        with:
          profile: ./writer/writer.out
          local-prefix: github.com/nafigator/zapper
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100

      - name: Check zapper package coverage
        uses: vladopajic/go-test-coverage@v2.11.2
        with:
          profile: ./zapper.out
          local-prefix: github.com/nafigator/zapper
          threshold-file: 100
          threshold-package: 100
          threshold-total: 100

      - name: Upload headers coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./conf/conf.out, ./writer/writer.out, ./zapper.out
          flags: unittests
          name: codecov-zapper
          verbose: false
